# header parameters
ContentTypeHeader:
  in: header
  name: Content-Type
  required: true
  schema:
    type: string
    default: application/json
AdminAPIKey:
  in: header
  name: x-api-key
  description: Admin API Key
  required: true
  schema:
    type: string
    description: Admin API Key
ProjectAPIKey:
  in: header
  name: x-api-key
  description: Project API Key
  required: true
  schema:
    type: string
    description: Project API Key

# path parameters
ProjectID:
  in: path
  name: projectId
  schema:
    type: string
IndexName:
  in: path
  name: indexName
  schema:
    type: string
